# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab45232f4b01b3505bf9f42bb1f0b0ed6206890be1ff375abdf5923cd3b02e9281969f0ad809a129e9febc625ec0d7f483e112bd3a455e6b16a5da0bf28c4d2e

test:
  secret_key_base: 6307ef226972d86355502ebe03778459460b38890bd05781619f23c10b9c482a954fc289ebf139ad2f07a47fbefddd0b00e274ad112b1fa713390cb953228b07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
